# vim: ft=yaml ts=2:
---
  
- name: include OS specific variables
  include_vars:
    file: "{{ ansible_os_family }}.yml"

- name: set facts
  set_fact:
    pki_dir: "{{ pki.dir|default(pki_defaults.dir) }}"
