# vim: ft=yaml ts=2:
---

- debug: var=pki
  tags:
    - never
    - debug

- name: assertions
  assert:
    that:
      - pki.dir|default(pki_defaults.dir) is defined
      - pki.name is defined
      - alias is defined
      

- name: create cnf
  template:
    src: "{{ playbook_dir }}/{{ cnf }}"
    dest: "{{ pki.dir|default(pki_defaults.dir) }}/{{ pki.name }}/etc/{{ alias }}.cnf"

- name: generate passphrase for the private key
  no_log: true
  copy:
    content: "{{ lookup('password', '/dev/null') }}"
    dest: "{{ pki.dir|default(pki_defaults.dir) }}/{{ pki.name }}/private/.{{ alias }}.passphrase"
    force: false
    mode: 00700

- name: create CSR
  command: openssl req -new -config etc/{{ alias }}.cnf -out certs/{{ alias }}.cert -passout file:{{ pki.dir|default(pki_defaults.dir) }}/{{ pki.name }}/private/.{{ alias }}.passphrase
  args:
    chdir: "{{ pki.dir|default(pki_defaults.dir) }}/{{ pki.name }}"
    creates: "{{ pki.dir|default(pki_defaults.dir) }}/{{ pki.name }}/csr/{{ alias }}.csr"
